# Generated by Django 5.2.13 on 2026-04-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('assignee', models.CharField(max_length=50)),
                ('deadline', models.DateField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
